In [4]:
import torch

In [5]:
#defining a sigmoid function
def activation(x):
    return 1/(1+torch.exp(-x))

In [8]:
#Generate fake data
torch.manual_seed(7)

#tensor of a sample from a normal distribution
features = torch.randn((1,5))

#tensor of normal variables with the same shape of the tensor features
weights = torch.randn_like((features))

#tensor of 1 row and 1 column
bias = torch.randn((1,1))

In [11]:
y = activation(torch.sum(features * weights) + bias)
print(y)

tensor([[0.1595]])


In [17]:
#Using matrix moltiplication
print(features.shape, weights.shape)
print(features.shape, weights.view(5,1).shape)

y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

torch.Size([1, 5]) torch.Size([1, 5])
torch.Size([1, 5]) torch.Size([5, 1])
tensor([[0.1595]])


#### Multi layer network

In [19]:
features = torch.randn((1,3))

#define the size of each layer
n_input = features.shape[1]          #number of input units
n_hidden = 2                         #number of hidden units
n_output = 1                         #number of output units

W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [20]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.5873]])


#### From Numpy to Pytorch

In [21]:
import numpy as np

In [23]:
a = np.random.rand(4,3)
a

array([[0.91754547, 0.64121016, 0.82846833],
       [0.59278211, 0.01710247, 0.76776419],
       [0.93125511, 0.26564783, 0.08945661],
       [0.76431223, 0.45923198, 0.33665555]])

In [25]:
b = torch.from_numpy(a)
b

tensor([[0.9175, 0.6412, 0.8285],
        [0.5928, 0.0171, 0.7678],
        [0.9313, 0.2656, 0.0895],
        [0.7643, 0.4592, 0.3367]], dtype=torch.float64)